### ISSUE TITLE
How to get multiple fields at once?

### ISSUE THREAD

**Issue by coodoo** [danidiaz/lens-aeson-examples#2]
Take this one for example, is it possible to get *just* `name` and `age` for each person? I tried some sort of `&&` operation on `key` but to no avail.

```
- Getting the names of all persons

  >>>persons ^.. values . key "name" . _String
  ["Alice","Bob","Jim"]
```

**Comment by danidiaz** [comment]
Added a new "Getting the names and ages of all persons" example which uses the `Applicative`  instance of the `Control.Lens.Reified.ReifiedFold` newtype to extract two fields at the same time.

**Comment by coodoo** [comment]
Cool, thanks!

**Comment by coodoo** [comment]
After having a detailed look I found this syntax a bit puzzle, mind elaborating?

```
let Fold nameAndAge = (,) <$> Fold (key "name"._String) <*> Fold (key "age"._Integer)
    ---------------
    ↑ what does this mean? 
    I had never saw a `let` declaration like this before.
   
in persons^..values.nameAndAge
```

At first look I thought you were constructing a Fold, with following format, but using the record syntax:

```
newtype ReifiedFold s a = Fold { runFold :: Fold s a }
                          ----------------------------
                          Fold nameAndAge
```
But was puzzled later when you use `nameAndAge` directly as in `persons^..values.nameAndAge`, I thought it should be used like this:

```
runFold aFold
```

**Comment by danidiaz** [comment]
That left side of the `let` declaration is not constructing a `ReifiedFold`, but pattern-matching on the single `Fold` constructor, so `nameAndAge` gets assigned a bare function that we can use directly (it's not that different from doing something like `let (a,b) = ...`)

Avoiding that pattern match and later using `runFold` would have worked as well.

**Comment by coodoo** [comment]
Oh right,  it's a `pattern matching`, how did I miss that!? Thanks for the clarification!! 👍👍
